@AspNetJsonHash.Api_HostAddress = http://localhost:5127

POST {{AspNetJsonHash.Api_HostAddress}}/objects
Content-Type: application/json
Accept-Language: pt-BR,pt

{
  "Name": "Leandro Yuri Joaquim Rodrigues"
}

###
